<?php

return [
    ['GET', '/', 'DashboardController@index'],
    ['GET', '/login', 'AuthController@login'],
    ['POST', '/login', 'AuthController@authenticate'],
    ['GET', '/auth/google', 'AuthController@redirectToGoogle'],
    ['GET', '/auth/google/callback', 'AuthController@googleCallback'],
    ['GET', '/auth/apple', 'AuthController@redirectToApple'],
    ['POST', '/auth/apple/callback', 'AuthController@appleCallback'],
    ['GET', '/auth/apple/callback', 'AuthController@appleCallback'],
    ['POST', '/logout', 'AuthController@logout'],
    ['GET', '/pos', 'PosController@index'],
    ['POST', '/pos/sale', 'PosController@store'],
    ['GET', '/caisse', 'PosController@index'],
    ['POST', '/caisse/vente', 'PosController@store'],
    ['GET', '/products', 'ProductController@index'],
    ['GET', '/products/create', 'ProductController@create'],
    ['POST', '/products', 'ProductController@store'],
    ['GET', '/products/{id}', 'ProductController@show'],
    ['GET', '/products/{id}/edit', 'ProductController@edit'],
    ['POST', '/products/{id}/update', 'ProductController@update'],
    ['POST', '/products/{id}/delete', 'ProductController@destroy'],
    ['GET', '/rapports/ventes', 'ReportController@sales'],
    ['GET', '/rapports/stock', 'ReportController@stockMovements'],
];
