<?php

$guest = ['guest'];
$protected = ['auth', 'blockAgentAdminAccess'];

return [
    ['GET', '/', 'HomeController@index'],
    ['GET', '/home', 'HomeController@index'],
    ['GET', '/accueil', 'HomeController@index'],
    ['GET', '/privacy', 'HomeController@privacy'],
    ['GET', '/confidentialite', 'HomeController@privacy'],
    ['GET', '/terms', 'HomeController@terms'],
    ['GET', '/conditions', 'HomeController@terms'],
    ['GET', '/dashboard', 'DashboardController@index', $protected],

    ['GET', '/login', 'AuthController@login', $guest],
    ['POST', '/login', 'AuthController@authenticate', $guest],
    ['POST', '/activate-account', 'AuthController@activateAccount', $guest],
    ['GET', '/activate', 'AuthController@activate', $guest],
    ['POST', '/activate', 'AuthController@activateWithCode', $guest],
    ['GET', '/logout', 'AuthController@logout', $protected],
    ['POST', '/logout', 'AuthController@logout', $protected],
    ['GET', '/auth/google', 'AuthController@redirectToGoogle', $guest],
    ['GET', '/auth/google/callback', 'AuthController@googleCallback', $guest],
    ['GET', '/auth/apple', 'AuthController@redirectToApple', $guest],
    ['POST', '/auth/apple/callback', 'AuthController@appleCallback', $guest],
    ['GET', '/auth/apple/callback', 'AuthController@appleCallback', $guest],
    ['GET', '/shops/create', 'ShopController@create', $protected],
    ['GET', '/boutiques/create', 'ShopController@create', $protected],

    ['GET', '/profil', 'UserController@profile', $protected],
    ['GET', '/profile', 'UserController@profile', $protected],
    ['GET', '/users', 'UserController@index', $protected],
    ['GET', '/users/create', 'UserController@create', $protected],
    ['POST', '/users', 'UserController@store', $protected],
    ['GET', '/admin/users/create', 'UserController@create', $protected],
    ['POST', '/admin/users', 'UserController@store', $protected],
    ['GET', '/customers', 'CustomerController@index', $protected],
    ['POST', '/customers', 'CustomerController@store', $protected],
    ['GET', '/customers/{id}', 'CustomerController@show', $protected],
    ['GET', '/customers/{id}/edit', 'CustomerController@edit', $protected],
    ['POST', '/customers/{id}/update', 'CustomerController@update', $protected],
    ['POST', '/customers/{id}/settle-debt', 'CustomerController@settleDebt'],
    ['POST', '/customers/{id}/delete', 'CustomerController@destroy', $protected],
    ['GET', '/clients', 'CustomerController@index', $protected],
    ['POST', '/clients', 'CustomerController@store', $protected],
    ['POST', '/clients/{id}/settle-debt', 'CustomerController@settleDebt'],
    ['GET', '/roles', 'RoleController@index', $protected],
    ['GET', '/roles/create', 'RoleController@create', $protected],
    ['POST', '/roles', 'RoleController@store', $protected],
    ['GET', '/roles-permissions', 'RoleController@index', $protected],

    ['GET', '/pos', 'PosController@index', $protected],
    ['GET', '/sales', 'PosController@sales', $protected],
    ['GET', '/ventes', 'PosController@sales', $protected],
    ['POST', '/pos/sale', 'PosController@store', $protected],
    ['GET', '/caisse', 'PosController@index', $protected],
    ['POST', '/caisse/vente', 'PosController@store', $protected],
    ['GET', '/pos', 'PosController@index'],
    ['GET', '/sales', 'PosController@sales'],
    ['GET', '/ventes', 'PosController@sales'],
    ['GET', '/sales/{id}', 'PosController@show'],
    ['GET', '/sales/{id}/edit', 'PosController@edit'],
    ['POST', '/sales/{id}/update', 'PosController@update'],
    ['POST', '/sales/{id}/delete', 'PosController@destroy'],
    ['GET', '/sales/{id}/invoice', 'PosController@invoice'],
    ['POST', '/pos/sale', 'PosController@store'],
    ['POST', '/pos/customer', 'PosController@storeCustomer'],
    ['GET', '/caisse', 'PosController@index'],
    ['POST', '/caisse/vente', 'PosController@store'],

    ['GET', '/products', 'ProductController@index', $protected],
    ['GET', '/products/create', 'ProductController@create', $protected],
    ['POST', '/products', 'ProductController@store', $protected],
    ['GET', '/products/{id}', 'ProductController@show', $protected],
    ['GET', '/products/{id}/edit', 'ProductController@edit', $protected],
    ['POST', '/products/{id}/update', 'ProductController@update', $protected],
    ['POST', '/products/{id}/delete', 'ProductController@destroy', $protected],

    ['GET', '/supplies', 'SupplyController@index', $protected],
    ['GET', '/supplies/create', 'SupplyController@create', $protected],
    ['POST', '/supplies', 'SupplyController@store', $protected],
    ['POST', '/supplies/create', 'SupplyController@store', $protected],
    ['GET', '/supplies/{id}', 'SupplyController@show', $protected],
    ['GET', '/suppliers', 'SupplierController@index', $protected],
    ['POST', '/suppliers', 'SupplierController@store', $protected],
    ['GET', '/suppliers/{id}', 'SupplierController@show', $protected],
    ['GET', '/suppliers/{id}/edit', 'SupplierController@edit', $protected],
    ['POST', '/suppliers/{id}/update', 'SupplierController@update', $protected],
    ['POST', '/suppliers/{id}/delete', 'SupplierController@destroy', $protected],
    ['GET', '/fournisseurs', 'SupplierController@index', $protected],
    ['POST', '/fournisseurs', 'SupplierController@store', $protected],

    ['GET', '/stock/movements', 'StockController@movements', $protected],
    ['GET', '/stock/adjustments', 'StockController@adjustments', $protected],
    ['POST', '/stock/adjustments', 'StockController@storeAdjustment', $protected],
    ['GET', '/stock', 'StockController@movements', $protected],

    ['GET', '/expenses', 'ExpenseController@index', $protected],
    ['GET', '/expenses/create', 'ExpenseController@create', $protected],
    ['POST', '/expenses', 'ExpenseController@store', $protected],
    ['GET', '/expenses/{id}', 'ExpenseController@show', $protected],
    ['GET', '/finances', 'ExpenseController@index', $protected],
    ['POST', '/finances', 'ExpenseController@store', $protected],

    ['GET', '/reports/financials', 'ReportController@financials', $protected],
    ['GET', '/reports/sales', 'ReportController@sales', $protected],
    ['GET', '/reports/stock', 'ReportController@stockMovements', $protected],
    ['GET', '/rapports/finances', 'ReportController@financials', $protected],
    ['GET', '/rapports/ventes', 'ReportController@sales', $protected],
    ['GET', '/rapports/stock', 'ReportController@stockMovements', $protected],
    ['GET', '/rapports/financiers', 'ReportController@financials', $protected],
    ['GET', '/backup/manual', 'ReportController@backup', $protected],
];
