<?php

$guest = ['guest'];
$protected = ['auth', 'blockAgentAdminAccess'];
$saasAdmin = ['auth', 'saasAdmin'];

return [
    ['GET', '/', 'HomeController@index'],
    ['GET', '/home', 'HomeController@index'],
    ['GET', '/accueil', 'HomeController@index'],
    ['GET', '/privacy', 'HomeController@privacy'],
    ['GET', '/confidentialite', 'HomeController@privacy'],
    ['GET', '/terms', 'HomeController@terms'],
    ['GET', '/conditions', 'HomeController@terms'],
    ['GET', '/dashboard', 'DashboardController@index', $protected],
    ['GET', '/saas-admin', 'SaasAdmin/SaasDashboardController@index', $saasAdmin],
    ['GET', '/saas-admin/boutiques', 'SaasAdmin/SaasShopController@index', $saasAdmin],
    ['GET', '/saas-admin/boutiques/create', 'SaasAdmin/SaasShopController@create', $saasAdmin],
    ['POST', '/saas-admin/boutiques', 'SaasAdmin/SaasShopController@store', $saasAdmin],
    ['GET', '/saas-admin/boutiques/{id}/access', 'SaasAdmin/SaasShopController@accessShop', $saasAdmin],
    ['GET', '/saas-admin/boutiques/{id}/edit', 'SaasAdmin/SaasShopController@edit', $saasAdmin],
    ['POST', '/saas-admin/boutiques/{id}/update', 'SaasAdmin/SaasShopController@update', $saasAdmin],
    ['POST', '/saas-admin/boutiques/{id}/toggle', 'SaasAdmin/SaasShopController@toggle', $saasAdmin],
    ['GET', '/saas-admin/espace-boutique', 'SaasAdmin/SaasShopController@select', $saasAdmin],
    ['GET', '/saas-admin/categories', 'SaasAdmin/SaasCategoryController@index', $saasAdmin],
    ['POST', '/saas-admin/categories', 'SaasAdmin/SaasCategoryController@store', $saasAdmin],
    ['POST', '/saas-admin/categories/{id}/update', 'SaasAdmin/SaasCategoryController@update', $saasAdmin],
    ['POST', '/saas-admin/categories/{id}/toggle', 'SaasAdmin/SaasCategoryController@toggle', $saasAdmin],
    ['GET', '/saas-admin/utilisateurs', 'SaasAdmin/SaasAccessController@users', $saasAdmin],
    ['GET', '/saas-admin/utilisateurs/{id}/edit', 'SaasAdmin/SaasAccessController@editUser', $saasAdmin],
    ['POST', '/saas-admin/utilisateurs/{id}/update', 'SaasAdmin/SaasAccessController@updateUser', $saasAdmin],
    ['GET', '/saas-admin/droits', 'SaasAdmin/SaasAccessController@roles', $saasAdmin],
    ['GET', '/saas-admin/droits/create', 'SaasAdmin/SaasAccessController@createRole', $saasAdmin],
    ['POST', '/saas-admin/droits', 'SaasAdmin/SaasAccessController@storeRole', $saasAdmin],
    ['GET', '/saas-admin/fonctionnalites', 'SaasAdmin/SaasFeatureController@index', $saasAdmin],
    ['POST', '/saas-admin/fonctionnalites', 'SaasAdmin/SaasFeatureController@store', $saasAdmin],
    ['POST', '/saas-admin/fonctionnalites/{id}/update', 'SaasAdmin/SaasFeatureController@update', $saasAdmin],
    ['POST', '/saas-admin/fonctionnalites/{id}/toggle', 'SaasAdmin/SaasFeatureController@toggle', $saasAdmin],
    ['POST', '/saas-admin/fonctionnalites/categories/{id}/plans', 'SaasAdmin/SaasFeatureController@syncCategoryPlans', $saasAdmin],
    ['POST', '/saas-admin/fonctionnalites/plans/{id}', 'SaasAdmin/SaasFeatureController@syncPlan', $saasAdmin],
    ['GET', '/saas-admin/abonnements', 'SaasAdmin/SaasSubscriptionController@index', $saasAdmin],
    ['POST', '/saas-admin/abonnements/plans', 'SaasAdmin/SaasSubscriptionController@storePlan', $saasAdmin],
    ['GET', '/saas-admin/abonnements/plans/{id}', 'SaasAdmin/SaasSubscriptionController@showPlan', $saasAdmin],
    ['GET', '/saas-admin/abonnements/plans/{id}/edit', 'SaasAdmin/SaasSubscriptionController@editPlan', $saasAdmin],
    ['POST', '/saas-admin/abonnements/plans/{id}/update', 'SaasAdmin/SaasSubscriptionController@updatePlan', $saasAdmin],
    ['POST', '/saas-admin/abonnements/plans/{id}/delete', 'SaasAdmin/SaasSubscriptionController@deletePlan', $saasAdmin],
    ['POST', '/saas-admin/abonnements/boutiques/{id}', 'SaasAdmin/SaasSubscriptionController@assign', $saasAdmin],
    ['GET', '/saas-admin/parametres', 'SaasAdmin/SaasSettingsController@index', $saasAdmin],
    ['POST', '/saas-admin/parametres', 'SaasAdmin/SaasSettingsController@update', $saasAdmin],
    ['GET', '/saas-admin/profil', 'SaasAdmin/SaasProfileController@index', $saasAdmin],
    ['POST', '/saas-admin/profil', 'SaasAdmin/SaasProfileController@update', $saasAdmin],
    ['POST', '/saas-admin/profil/password', 'SaasAdmin/SaasProfileController@updatePassword', $saasAdmin],

    ['GET', '/login', 'AuthController@login', $guest],
    ['POST', '/login', 'AuthController@authenticate', $guest],
    ['POST', '/activate-account', 'AuthController@activateAccount', $guest],
    ['GET', '/activate', 'AuthController@activate', $guest],
    ['POST', '/activate', 'AuthController@activateWithCode', $guest],
    ['GET', '/logout', 'AuthController@logout', $protected],
    ['POST', '/logout', 'AuthController@logout', $protected],
    ['GET', '/auth/google', 'AuthController@redirectToGoogle', $guest],
    ['GET', '/auth/google/callback', 'AuthController@googleCallback', $guest],
    ['GET', '/auth/apple', 'AuthController@redirectToApple', $guest],
    ['POST', '/auth/apple/callback', 'AuthController@appleCallback', $guest],
    ['GET', '/auth/apple/callback', 'AuthController@appleCallback', $guest],
    ['GET', '/shops/create', 'ShopController@create', $protected],
    ['GET', '/boutiques/create', 'ShopController@create', $protected],
    ['GET', '/shops/settings', 'ShopController@settings', $protected],
    ['POST', '/shops/settings', 'ShopController@updateSettings', $protected],
    ['GET', '/boutiques/parametres', 'ShopController@settings', $protected],
    ['POST', '/boutiques/parametres', 'ShopController@updateSettings', $protected],

    ['GET', '/profil', 'UserController@profile', $protected],
    ['GET', '/profile', 'UserController@profile', $protected],
    ['GET', '/users', 'UserController@index', $protected],
    ['GET', '/users/create', 'UserController@create', $protected],
    ['POST', '/users', 'UserController@store', $protected],
    ['GET', '/users/{id}/edit', 'UserController@edit', $protected],
    ['POST', '/users/{id}/update', 'UserController@update', $protected],
    ['POST', '/users/{id}/delete', 'UserController@delete', $protected],
    ['GET', '/admin/users', 'UserController@index', $protected],
    ['GET', '/admin/users/create', 'UserController@create', $protected],
    ['POST', '/admin/users', 'UserController@store', $protected],
    ['GET', '/admin/users/edit/{id}', 'UserController@edit', $protected],
    ['POST', '/admin/users/update/{id}', 'UserController@update', $protected],
    ['POST', '/admin/users/delete/{id}', 'UserController@delete', $protected],
    ['GET', '/customers', 'CustomerController@index', $protected],
    ['POST', '/customers', 'CustomerController@store', $protected],
    ['GET', '/customers/{id}', 'CustomerController@show', $protected],
    ['GET', '/customers/{id}/edit', 'CustomerController@edit', $protected],
    ['POST', '/customers/{id}/update', 'CustomerController@update', $protected],
    ['POST', '/customers/{id}/settle-debt', 'CustomerController@settleDebt'],
    ['POST', '/customers/{id}/delete', 'CustomerController@destroy', $protected],
    ['GET', '/clients', 'CustomerController@index', $protected],
    ['POST', '/clients', 'CustomerController@store', $protected],
    ['POST', '/clients/{id}/settle-debt', 'CustomerController@settleDebt'],
    ['GET', '/roles', 'RoleController@index', $protected],
    ['GET', '/roles/create', 'RoleController@create', $protected],
    ['POST', '/roles', 'RoleController@store', $protected],
    ['GET', '/roles-permissions', 'RoleController@index', $protected],

    ['GET', '/pos', 'PosController@index', $protected],
    ['GET', '/sales', 'PosController@sales', $protected],
    ['GET', '/ventes', 'PosController@sales', $protected],
    ['POST', '/pos/sale', 'PosController@store', $protected],
    ['GET', '/caisse', 'PosController@index', $protected],
    ['POST', '/caisse/vente', 'PosController@store', $protected],
    ['GET', '/pos', 'PosController@index'],
    ['GET', '/sales', 'PosController@sales'],
    ['GET', '/ventes', 'PosController@sales'],
    ['GET', '/sales/{id}', 'PosController@show'],
    ['GET', '/sales/{id}/edit', 'PosController@edit'],
    ['POST', '/sales/{id}/update', 'PosController@update'],
    ['POST', '/sales/{id}/delete', 'PosController@destroy'],
    ['GET', '/sales/{id}/invoice', 'PosController@invoice'],
    ['POST', '/pos/sale', 'PosController@store'],
    ['POST', '/pos/customer', 'PosController@storeCustomer'],
    ['GET', '/caisse', 'PosController@index'],
    ['POST', '/caisse/vente', 'PosController@store'],

    ['GET', '/products', 'ProductController@index', $protected],
    ['GET', '/products/create', 'ProductController@create', $protected],
    ['POST', '/products', 'ProductController@store', $protected],
    ['GET', '/products/{id}', 'ProductController@show', $protected],
    ['GET', '/products/{id}/edit', 'ProductController@edit', $protected],
    ['POST', '/products/{id}/update', 'ProductController@update', $protected],
    ['POST', '/products/{id}/delete', 'ProductController@destroy', $protected],

    ['GET', '/supplies', 'SupplyController@index', $protected],
    ['GET', '/supplies/create', 'SupplyController@create', $protected],
    ['POST', '/supplies', 'SupplyController@store', $protected],
    ['POST', '/supplies/create', 'SupplyController@store', $protected],
    ['GET', '/supplies/{id}/edit', 'SupplyController@edit', $protected],
    ['POST', '/supplies/{id}/update', 'SupplyController@update', $protected],
    ['POST', '/supplies/{id}/cancel', 'SupplyController@cancel', $protected],
    ['GET', '/supplies/{id}', 'SupplyController@show', $protected],
    ['GET', '/suppliers', 'SupplierController@index', $protected],
    ['POST', '/suppliers', 'SupplierController@store', $protected],
    ['GET', '/suppliers/{id}', 'SupplierController@show', $protected],
    ['GET', '/suppliers/{id}/edit', 'SupplierController@edit', $protected],
    ['POST', '/suppliers/{id}/update', 'SupplierController@update', $protected],
    ['POST', '/suppliers/{id}/delete', 'SupplierController@destroy', $protected],
    ['GET', '/fournisseurs', 'SupplierController@index', $protected],
    ['POST', '/fournisseurs', 'SupplierController@store', $protected],

    ['GET', '/stock/movements', 'StockController@movements', $protected],
    ['GET', '/stock/adjustments', 'StockController@adjustments', $protected],
    ['POST', '/stock/adjustments', 'StockController@storeAdjustment', $protected],
    ['GET', '/stock', 'StockController@movements', $protected],

    ['GET', '/expenses', 'ExpenseController@index', $protected],
    ['GET', '/expenses/create', 'ExpenseController@create', $protected],
    ['POST', '/expenses', 'ExpenseController@store', $protected],
    ['GET', '/expenses/{id}', 'ExpenseController@show', $protected],
    ['POST', '/expenses/{id}/update', 'ExpenseController@update', $protected],
    ['POST', '/expenses/{id}/cancel', 'ExpenseController@cancel', $protected],
    ['GET', '/finances', 'ExpenseController@index', $protected],
    ['POST', '/finances', 'ExpenseController@store', $protected],
    ['POST', '/finances/{id}/update', 'ExpenseController@update', $protected],
    ['POST', '/finances/{id}/cancel', 'ExpenseController@cancel', $protected],

    ['GET', '/reports/financials', 'ReportController@financials', $protected],
    ['GET', '/reports/sales', 'ReportController@sales', $protected],
    ['GET', '/reports/stock', 'ReportController@stockMovements', $protected],
    ['GET', '/rapports/finances', 'ReportController@financials', $protected],
    ['GET', '/rapports/ventes', 'ReportController@sales', $protected],
    ['GET', '/rapports/stock', 'ReportController@stockMovements', $protected],
    ['GET', '/rapports/financiers', 'ReportController@financials', $protected],
    ['GET', '/backup/manual', 'ReportController@backup', $protected],
];
