CREATE TABLE IF NOT EXISTS saas_subscription_payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  shop_id BIGINT UNSIGNED NOT NULL,
  subscription_id BIGINT UNSIGNED NULL,
  plan_id BIGINT UNSIGNED NULL,
  montant_usd DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  devise ENUM('USD', 'CDF') NOT NULL DEFAULT 'USD',
  periode_debut DATE NULL,
  periode_fin DATE NULL,
  statut ENUM('pending', 'paid', 'failed', 'cancelled') NOT NULL DEFAULT 'pending',
  mode_paiement VARCHAR(50) NULL,
  reference VARCHAR(100) NULL,
  notes TEXT NULL,
  paid_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_saas_subscription_payments_shop (shop_id),
  KEY idx_saas_subscription_payments_subscription (subscription_id),
  KEY idx_saas_subscription_payments_plan (plan_id),
  KEY idx_saas_subscription_payments_statut (statut),
  CONSTRAINT fk_saas_subscription_payments_shop FOREIGN KEY (shop_id) REFERENCES shops(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_saas_subscription_payments_subscription FOREIGN KEY (subscription_id) REFERENCES saas_subscriptions(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_saas_subscription_payments_plan FOREIGN KEY (plan_id) REFERENCES saas_subscription_plans(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
