<?php
$operators=is_array($operators??null)?$operators:[];$mobileProducts=is_array($mobileProducts??null)?$mobileProducts:[];$mobileSupplies=is_array($mobileSupplies??null)?$mobileSupplies:[];$mobileSales=is_array($mobileSales??null)?$mobileSales:[];$section=(string)($mobileSection??'dashboard');$mobileEmployees=is_array($mobileEmployees??null)?$mobileEmployees:[];$mobileCustomers=is_array($mobileCustomers??null)?$mobileCustomers:[];$salesFilters=is_array($salesFilters??null)?$salesFilters:[];
$safe=static fn($v,$f='—'):string=>htmlspecialchars((string)(($v??'')!==''?$v:$f),ENT_QUOTES,'UTF-8');
$fmt=static fn($v):string=>number_format((float)$v,2,',',' ');
$stockTotal=array_sum(array_map(static fn($p)=>(float)($p['stock_actuel']??0),$mobileProducts));$commissionTotal=array_sum(array_map(static fn($s)=>(float)($s['commission']??0),$mobileSales));
$nav=['dashboard'=>['Vue générale','/forfaits-unites'],'operators'=>['Opérateurs','/forfaits-unites/operateurs'],'products'=>['Produits','/forfaits-unites/produits'],'stock'=>['Stock virtuel','/forfaits-unites/stock'],'supplies'=>['Approvisionnements','/forfaits-unites/approvisionnements'],'sales'=>['Nouvelle vente','/forfaits-unites/ventes'],'history'=>['Historique des ventes','/forfaits-unites/historique']];
?>
<section class="space-y-5" data-mobile-units>
 <div class="relative overflow-hidden rounded-2xl bg-gradient-to-br from-blue-950 via-violet-950 to-fuchsia-800 p-6 text-white shadow-xl sm:p-8"><div class="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl"></div><div class="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div class="flex items-center gap-3"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-white/10 text-2xl">📶</span><div><p class="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Télécom & Mobile</p><p class="mt-1 text-sm text-white/60">Vente de forfaits et unités</p></div></div><h1 class="mt-5 text-3xl font-black sm:text-4xl"><?= $safe($nav[$section][0]??'Centre de gestion mobile') ?></h1><p class="mt-3 max-w-2xl text-sm leading-7 text-white/70">Chaque fonction est disponible dans son propre module depuis le menu de navigation.</p></div><?php if($section!=='sales'): ?><a class="rounded-xl bg-cyan-400 px-5 py-3 text-center text-sm font-black text-slate-950 hover:bg-cyan-300" href="<?= $url('/forfaits-unites/ventes') ?>">+ Nouvelle vente</a><?php endif; ?></div></div>

 <?php if($section==='dashboard'): ?>
 <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><?php foreach([['Opérateurs actifs',count(array_filter($operators,fn($o)=>(int)$o['actif']===1)),'text-violet-700'],['Produits mobiles',count($mobileProducts),'text-blue-700'],['Solde virtuel total',$fmt($stockTotal),'text-teal-700'],['Commissions ventes',$fmt($commissionTotal).' CDF','text-fuchsia-700']] as [$l,$v,$c]): ?><article class="stat-card"><p class="text-sm text-slate-500"><?= $safe($l) ?></p><p class="mt-2 text-2xl font-black <?= $c ?>"><?= $safe($v) ?></p></article><?php endforeach; ?></div>
 <div class="grid gap-5 lg:grid-cols-2"><section class="surface-panel"><div class="panel-header"><div><h2 class="text-lg font-bold">Opérateurs</h2><p class="mt-1 text-sm text-slate-500">Réseaux configurés dans la boutique.</p></div><a class="btn-secondary" href="<?= $url('/forfaits-unites/operateurs') ?>">Gérer</a></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><?php foreach($operators as $o): ?><div class="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><span class="grid h-11 w-11 place-items-center overflow-hidden rounded-xl text-lg font-black text-white" style="background:<?= $safe($o['couleur']) ?>"><?php if($o['logo_url']): ?><img class="h-full w-full object-cover" src="<?= $safe($o['logo_url']) ?>" alt=""><?php else: ?><?= $safe(substr($o['nom'],0,1)) ?><?php endif; ?></span><div><strong><?= $safe($o['nom']) ?></strong><span class="block text-xs text-slate-500"><?= $safe($o['code_ussd'],'Code non défini') ?></span></div></div><?php endforeach; ?></div></section>
 <section class="surface-panel"><div class="panel-header"><div><h2 class="text-lg font-bold">Dernières opérations</h2><p class="mt-1 text-sm text-slate-500">Approvisionnements et ventes récents.</p></div></div><div class="mt-4 space-y-2"><?php foreach(array_slice($mobileSales,0,5) as $sale): ?><div class="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><div><strong class="text-sm"><?= $safe($sale['operator_name'].' · '.$sale['product_name']) ?></strong><span class="block text-xs text-slate-500"><?= $safe($sale['reference']) ?></span></div><span class="font-black text-violet-700">-<?= $fmt($sale['quantite']) ?> <?= $safe($sale['unite']) ?></span></div><?php endforeach; ?><?php if(!$mobileSales): ?><p class="py-8 text-center text-sm text-slate-500">Aucune vente enregistrée.</p><?php endif; ?></div></section></div>
 <?php endif; ?>

 <?php if($section==='operators'): ?>
 <div class="grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><form class="surface-panel h-fit space-y-4" method="post" action="<?= $url('/forfaits-unites/operateurs') ?>"><div><p class="text-xs font-black uppercase tracking-[.16em] text-violet-700">Nouvel opérateur</p><h2 class="mt-2 text-xl font-bold">Créer un réseau</h2></div><label class="form-field"><span>Nom</span><input name="nom" required placeholder="Ex. Airtel"></label><label class="form-field"><span>URL du logo</span><input name="logo_url" type="url" placeholder="https://..."></label><div class="grid grid-cols-2 gap-3"><label class="form-field"><span>Code USSD</span><input name="code_ussd" placeholder="*121#"></label><label class="form-field"><span>Couleur</span><input class="h-12" name="couleur" type="color" value="#7c3aed"></label></div><label class="form-field"><span>Numéro principal</span><input name="numero_principal" placeholder="+243..."></label><label class="flex gap-3 rounded-xl bg-teal-50 p-3 text-sm font-bold"><input type="checkbox" name="actif" value="1" checked> Opérateur actif</label><button class="btn-primary w-full">Créer l’opérateur</button></form>
 <div class="grid gap-4 md:grid-cols-2"><?php foreach($operators as $o): ?><form class="surface-panel space-y-4" method="post" action="<?= $url('/forfaits-unites/operateurs/'.(int)$o['id'].'/update') ?>"><div class="flex items-center gap-3"><span class="grid h-12 w-12 place-items-center overflow-hidden rounded-xl font-black text-white" style="background:<?= $safe($o['couleur']) ?>"><?php if($o['logo_url']): ?><img class="h-full w-full object-cover" src="<?= $safe($o['logo_url']) ?>" alt=""><?php else: ?><?= $safe(substr($o['nom'],0,1)) ?><?php endif; ?></span><div><strong><?= $safe($o['nom']) ?></strong><span class="block text-xs <?= (int)$o['actif']?'text-teal-600':'text-red-600' ?>"><?= (int)$o['actif']?'Actif':'Inactif' ?></span></div></div><label class="form-field"><span>Nom</span><input name="nom" value="<?= $safe($o['nom']) ?>"></label><label class="form-field"><span>Logo</span><input name="logo_url" value="<?= $safe($o['logo_url'],'') ?>"></label><div class="grid grid-cols-2 gap-3"><label class="form-field"><span>USSD</span><input name="code_ussd" value="<?= $safe($o['code_ussd'],'') ?>"></label><label class="form-field"><span>Couleur</span><input class="h-12" name="couleur" type="color" value="<?= $safe($o['couleur']) ?>"></label></div><label class="form-field"><span>Numéro principal</span><input name="numero_principal" value="<?= $safe($o['numero_principal'],'') ?>"></label><label class="flex gap-2 text-sm font-bold"><input type="checkbox" name="actif" value="1" <?= (int)$o['actif']?'checked':'' ?>> Actif</label><div class="flex gap-2"><button class="btn-primary flex-1">Enregistrer</button><button class="btn-secondary" formaction="<?= $url('/forfaits-unites/operateurs/'.(int)$o['id'].'/toggle') ?>"><?= (int)$o['actif']?'Désactiver':'Activer' ?></button></div></form><?php endforeach; ?></div></div>
 <?php endif; ?>

 <?php if($section==='products'): ?>
 <script type="application/json" data-mobile-products-json><?= json_encode($mobileProducts,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?></script>
 <div class="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><form class="surface-panel h-fit space-y-4" method="post" action="<?= $url('/forfaits-unites/produits') ?>"><div><p class="text-xs font-black uppercase tracking-[.16em] text-blue-700">Nouveau produit</p><h2 class="mt-2 text-xl font-bold">Créer une offre mobile</h2></div><label class="form-field"><span>Opérateur</span><select name="operator_id" required><option value="">Sélectionner</option><?php foreach($operators as $o): ?><option value="<?= (int)$o['id'] ?>"><?= $safe($o['nom']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Nom</span><input name="nom" required placeholder="Ex. Forfait Internet 5 Go"></label><div class="grid grid-cols-2 gap-3"><label class="form-field"><span>Catégorie</span><select name="categorie"><option>Crédit</option><option>SMS</option><option>Minutes</option><option>Internet</option><option>Forfait journalier</option><option>Forfait hebdomadaire</option><option>Forfait mensuel</option></select></label><label class="form-field"><span>Unité de stock</span><select name="unite"><option>CDF</option><option>GO</option><option>MINUTES</option><option>SMS</option><option>UNITES</option></select></label></div><div class="grid grid-cols-2 gap-3"><label class="form-field"><span>Prix d’achat</span><input name="prix_achat" type="number" min="0" step="0.01"></label><label class="form-field"><span>Prix de vente</span><input name="prix_vente" type="number" min="0" step="0.01"></label></div><div class="grid grid-cols-2 gap-3"><label class="form-field"><span>Commission</span><input name="commission" type="number" min="0" step="0.01"></label><label class="form-field"><span>Stock initial</span><input name="stock_initial" type="number" min="0" step="0.01"></label></div><label class="form-field"><span>Description</span><textarea name="description" rows="3"></textarea></label><label class="flex gap-2 text-sm font-bold"><input type="checkbox" name="actif" value="1" checked> Produit actif</label><button class="btn-primary w-full">Enregistrer le produit</button></form>
 <section class="surface-panel overflow-hidden p-0"><div class="p-5"><h2 class="text-xl font-bold">Produits par opérateur</h2><p class="mt-1 text-sm text-slate-500">Crédit, SMS, minutes, Internet et forfaits périodiques.</p></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Opérateur</th><th>Produit</th><th>Catégorie</th><th>Achat</th><th>Vente</th><th>Commission</th><th>Stock</th><th>Action</th></tr></thead><tbody><?php foreach($mobileProducts as $p): ?><tr><td><span class="rounded-lg px-2 py-1 text-xs font-black text-white" style="background:<?= $safe($p['operator_color']) ?>"><?= $safe($p['operator_name']) ?></span></td><td><strong><?= $safe($p['nom']) ?></strong><span class="block text-xs text-slate-500"><?= $safe($p['description']) ?></span></td><td><?= $safe($p['categorie']) ?></td><td><?= $fmt($p['prix_achat']) ?></td><td><?= $fmt($p['prix_vente']) ?></td><td><?= $fmt($p['commission']) ?></td><td class="font-black text-teal-700"><?= $fmt($p['stock_actuel']) ?> <?= $safe($p['unite']) ?></td><td><button class="btn-secondary h-9 px-3 text-xs" type="button" data-mobile-product-edit="<?= (int)$p['id'] ?>">Modifier</button></td></tr><?php endforeach; ?></tbody></table></div></section></div>
 <?php foreach($mobileProducts as $p): ?><div class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/60 p-4" data-mobile-product-modal="<?= (int)$p['id'] ?>"><form class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" method="post" action="<?= $url('/forfaits-unites/produits/'.(int)$p['id'].'/update') ?>"><div class="flex items-start justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-violet-700">Modification produit</p><h2 class="mt-2 text-xl font-bold"><?= $safe($p['nom']) ?></h2></div><button class="rounded-lg border px-3 py-2" type="button" data-mobile-product-close>✕</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="form-field"><span>Opérateur</span><select name="operator_id"><?php foreach($operators as $o): ?><option value="<?= (int)$o['id'] ?>" <?= (int)$p['operator_id']===(int)$o['id']?'selected':'' ?>><?= $safe($o['nom']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Nom</span><input name="nom" value="<?= $safe($p['nom']) ?>"></label><label class="form-field"><span>Catégorie</span><input name="categorie" value="<?= $safe($p['categorie']) ?>"></label><label class="form-field"><span>Unité</span><select name="unite"><?php foreach(['CDF','GO','MINUTES','SMS','UNITES'] as $u): ?><option <?= $p['unite']===$u?'selected':'' ?>><?= $u ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Prix d’achat</span><input name="prix_achat" type="number" step="0.01" value="<?= $safe($p['prix_achat']) ?>"></label><label class="form-field"><span>Prix de vente</span><input name="prix_vente" type="number" step="0.01" value="<?= $safe($p['prix_vente']) ?>"></label><label class="form-field"><span>Commission</span><input name="commission" type="number" step="0.01" value="<?= $safe($p['commission']) ?>"></label><label class="form-field"><span>Stock initial</span><input name="stock_initial" type="number" step="0.01" value="<?= $safe($p['stock_initial']) ?>"></label><label class="form-field sm:col-span-2"><span>Description</span><textarea name="description"><?= $safe($p['description'],'') ?></textarea></label><label class="flex gap-2 text-sm font-bold"><input type="checkbox" name="actif" value="1" <?= (int)$p['actif']?'checked':'' ?>> Produit actif</label></div><div class="mt-5 flex justify-end gap-3"><button class="btn-secondary" type="button" data-mobile-product-close>Annuler</button><button class="btn-primary">Enregistrer les modifications</button></div></form></div><?php endforeach; ?>
 <?php endif; ?>

 <?php if($section==='stock'): ?>
 <div class="grid gap-5 lg:grid-cols-2"><?php foreach($operators as $o): ?><section class="surface-panel"><div class="flex items-center gap-3 border-b border-slate-100 pb-4"><span class="grid h-11 w-11 place-items-center rounded-xl font-black text-white" style="background:<?= $safe($o['couleur']) ?>"><?= $safe(substr($o['nom'],0,1)) ?></span><div><h2 class="text-lg font-bold"><?= $safe($o['nom']) ?></h2><p class="text-xs text-slate-500">Soldes disponibles en temps réel</p></div></div><div class="mt-4 space-y-3"><?php foreach(array_filter($mobileProducts,fn($p)=>(int)$p['operator_id']===(int)$o['id']) as $p): ?><div class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between"><div><strong><?= $safe($p['nom']) ?></strong><span class="block text-xs text-slate-500"><?= $safe($p['categorie']) ?></span></div><span class="text-lg font-black <?= (float)$p['stock_actuel']<=0?'text-red-700':'text-teal-700' ?>"><?= $fmt($p['stock_actuel']) ?> <?= $safe($p['unite']) ?></span></div><div class="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><span class="rounded-lg bg-slate-50 p-2">Initial<br><b><?= $fmt($p['stock_initial']) ?></b></span><span class="rounded-lg bg-blue-50 p-2 text-blue-700">+ Appro.<br><b><?= $fmt($p['total_approvisionne']) ?></b></span><span class="rounded-lg bg-violet-50 p-2 text-violet-700">− Ventes<br><b><?= $fmt($p['total_vendu']) ?></b></span></div></div><?php endforeach; ?></div></section><?php endforeach; ?></div>
 <?php endif; ?>

 <?php if($section==='history'): ?>
 <form class="surface-panel grid gap-3 md:grid-cols-2 xl:grid-cols-6" method="get" action="<?= $url('/forfaits-unites/historique') ?>"><label class="form-field"><span>Date début</span><input name="date_from" type="date" value="<?= $safe($salesFilters['date_from']??'','') ?>"></label><label class="form-field"><span>Date fin</span><input name="date_to" type="date" value="<?= $safe($salesFilters['date_to']??'','') ?>"></label><label class="form-field"><span>Opérateur</span><select name="operator_id"><option value="0">Tous</option><?php foreach($operators as $o): ?><option value="<?= (int)$o['id'] ?>" <?= (int)($salesFilters['operator_id']??0)===(int)$o['id']?'selected':'' ?>><?= $safe($o['nom']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Employé</span><select name="user_id"><option value="0">Tous</option><?php foreach($mobileEmployees as $e): ?><option value="<?= (int)$e['id'] ?>" <?= (int)($salesFilters['user_id']??0)===(int)$e['id']?'selected':'' ?>><?= $safe($e['nom']??$e['email']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Client / numéro</span><input name="client" value="<?= $safe($salesFilters['client']??'','') ?>"></label><div class="flex items-end gap-2"><button class="btn-primary flex-1">Filtrer</button><a class="btn-secondary" href="<?= $url('/forfaits-unites/historique') ?>">Effacer</a></div><div class="flex gap-2 md:col-span-2 xl:col-span-6"><a class="btn-secondary" href="<?= $url('/forfaits-unites/historique',array_merge($salesFilters,['format'=>'excel'])) ?>">Exporter Excel</a><a class="btn-secondary" target="_blank" href="<?= $url('/forfaits-unites/historique',array_merge($salesFilters,['format'=>'pdf'])) ?>">Exporter PDF</a><span class="ml-auto self-center text-sm text-slate-500"><?= count($mobileSales) ?> vente(s)</span></div></form>
 <section class="surface-panel overflow-hidden p-0"><div class="p-5"><h2 class="text-xl font-bold">Historique des ventes</h2><p class="mt-1 text-sm text-slate-500">Toutes les ventes, employés, clients, bénéficiaires et bénéfices.</p></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Date</th><th>Opérateur</th><th>Produit</th><th>Employé</th><th>Client / bénéficiaire</th><th>Montant</th><th>Bénéfice</th><th>Référence</th><th>Reçu</th></tr></thead><tbody><?php foreach($mobileSales as $row): ?><tr><td><?= $safe($row['date_operation']) ?></td><td><?= $safe($row['operator_name']) ?></td><td><?= $safe($row['product_name']) ?></td><td><?= $safe($row['employee_name']) ?></td><td><?= $safe(($row['client_name']?:'—').' · '.($row['numero_client']?:'—')) ?></td><td class="font-bold"><?= $fmt($row['montant']) ?> CDF</td><td class="font-black text-teal-700"><?= $fmt($row['benefice']) ?> CDF</td><td><?= $safe($row['reference']) ?></td><td><a class="btn-secondary h-9 px-3 text-xs" href="<?= $url('/forfaits-unites/ventes/'.(int)$row['id'].'/recu') ?>">Imprimer</a></td></tr><?php endforeach; ?><?php if(!$mobileSales): ?><tr><td colspan="9" class="py-12 text-center text-slate-500">Aucune vente ne correspond aux filtres.</td></tr><?php endif; ?></tbody></table></div></section>
 <?php endif; ?>

 <?php if($section==='supplies'||$section==='sales'): $isSupply=$section==='supplies'; ?>
 <?php if($isSupply): ?><script type="application/json" data-mobile-supplies-json><?= json_encode($mobileSupplies,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?></script><?php endif; ?>
 <?php if(!$isSupply): ?><style>form[method="get"][action$="/forfaits-unites/ventes"],form[action$="/forfaits-unites/ventes"]:not([data-quick-sale-form]),form[action$="/forfaits-unites/ventes"] + section{display:none}.grid:has(> form[action$="/forfaits-unites/ventes"]){display:none!important}</style><?php endif; ?>
 <?php if(!$isSupply): ?>
 <section class="surface-panel"><div><p class="text-xs font-black uppercase tracking-[.16em] text-fuchsia-700">Vente rapide</p><h2 class="mt-2 text-xl font-bold">Vente d’unités par numéro</h2><p class="mt-1 text-sm text-slate-500">Sélectionnez le client ou ajoutez-le directement s’il est nouveau.</p></div>
 <script type="application/json" data-mobile-customers-json><?= json_encode($mobileCustomers,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?></script>
 <form class="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5" method="post" action="<?= $url('/forfaits-unites/ventes') ?>" data-quick-sale-form data-customer-endpoint="<?= $url('/pos/customer') ?>"><label class="form-field"><span>Opérateur</span><select name="operator_id" required data-mobile-operator><option value="">Choisir</option><?php foreach($operators as $o): ?><option value="<?= (int)$o['id'] ?>"><?= $safe($o['nom']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Produit</span><select name="product_id" required data-mobile-product><option value="">Choisir</option><?php foreach($mobileProducts as $p): ?><option value="<?= (int)$p['id'] ?>" data-operator="<?= (int)$p['operator_id'] ?>"><?= $safe($p['nom']) ?></option><?php endforeach; ?></select></label><div class="relative"><label class="form-field"><span>Client (facultatif)</span><input name="client_name" autocomplete="off" data-mobile-customer-search><input name="customer_id" type="hidden" data-mobile-customer-id></label><div class="absolute z-20 mt-1 hidden w-full overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl" data-mobile-customer-results></div><button class="mt-2 hidden w-full rounded-xl border border-dashed border-violet-300 bg-violet-50 px-3 py-2 text-sm font-bold text-violet-700" type="button" data-mobile-customer-add>+ Ajouter ce client</button><div class="mt-2 hidden space-y-2 rounded-xl border border-violet-200 bg-violet-50 p-3" data-mobile-customer-create><input class="field-control" type="tel" placeholder="Téléphone du client" data-mobile-customer-phone><div class="flex gap-2"><button class="btn-secondary h-10" type="button" data-mobile-customer-cancel>Annuler</button><button class="btn-primary h-10" type="button" data-mobile-customer-save>Enregistrer</button></div></div></div><label class="form-field"><span>Numéro bénéficiaire</span><input name="numero_client" required placeholder="099xxxxxxx"></label><label class="form-field"><span>Montant</span><input name="montant" type="number" min="1" required data-quick-amount></label><input name="quantite" type="hidden" data-quick-quantity><input name="reference" type="hidden" value="<?= $safe('VQR-'.date('Ymd-His')) ?>"><div class="md:col-span-2 xl:col-span-5"><button class="btn-primary">Vérifier et vendre</button></div></form></section>
 <section class="surface-panel overflow-hidden p-0"><div class="flex items-center justify-between gap-3 p-5"><div><h2 class="text-xl font-bold">10 dernières ventes</h2><p class="mt-1 text-sm text-slate-500">Les opérations les plus récentes de la boutique.</p></div><a class="btn-secondary h-10 w-auto" href="<?= $url('/forfaits-unites/historique') ?>">Tout voir</a></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Date</th><th>Client</th><th>Opérateur</th><th>Produit</th><th>Numéro</th><th>Montant</th><th>Bénéfice</th><th>Reçu</th></tr></thead><tbody><?php foreach(array_slice($mobileSales,0,10) as $row): ?><tr><td><?= $safe($row['date_operation']) ?></td><td><?= $safe($row['client_name'],'—') ?></td><td><?= $safe($row['operator_name']) ?></td><td><?= $safe($row['product_name']) ?></td><td><?= $safe($row['numero_client']) ?></td><td class="font-bold"><?= $fmt($row['montant']) ?> CDF</td><td class="font-bold text-emerald-700"><?= $fmt($row['benefice']) ?> CDF</td><td><a class="btn-secondary h-9 w-auto px-3 text-xs" href="<?= $url('/forfaits-unites/ventes/'.(int)$row['id'].'/recu') ?>">Imprimer</a></td></tr><?php endforeach; ?><?php if(!$mobileSales): ?><tr><td colspan="8" class="py-10 text-center text-slate-500">Aucune vente enregistrée.</td></tr><?php endif; ?></tbody></table></div></section>
 <form class="surface-panel grid gap-3 md:grid-cols-2 xl:grid-cols-6" method="get" action="<?= $url('/forfaits-unites/ventes') ?>"><label class="form-field"><span>Date début</span><input name="date_from" type="date" value="<?= $safe($salesFilters['date_from']??'','') ?>"></label><label class="form-field"><span>Date fin</span><input name="date_to" type="date" value="<?= $safe($salesFilters['date_to']??'','') ?>"></label><label class="form-field"><span>Opérateur</span><select name="operator_id"><option value="0">Tous</option><?php foreach($operators as $o): ?><option value="<?= (int)$o['id'] ?>" <?= (int)($salesFilters['operator_id']??0)===(int)$o['id']?'selected':'' ?>><?= $safe($o['nom']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Employé</span><select name="user_id"><option value="0">Tous</option><?php foreach($mobileEmployees as $e): ?><option value="<?= (int)$e['id'] ?>" <?= (int)($salesFilters['user_id']??0)===(int)$e['id']?'selected':'' ?>><?= $safe($e['nom']??$e['email']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Client / numéro</span><input name="client" value="<?= $safe($salesFilters['client']??'','') ?>"></label><div class="flex items-end gap-2"><button class="btn-primary flex-1">Filtrer</button><a class="btn-secondary" href="<?= $url('/forfaits-unites/ventes') ?>">Effacer</a></div><div class="flex gap-2 md:col-span-2 xl:col-span-6"><a class="btn-secondary" href="<?= $url('/forfaits-unites/ventes',array_merge($salesFilters,['format'=>'excel'])) ?>">Exporter Excel</a><a class="btn-secondary" target="_blank" href="<?= $url('/forfaits-unites/ventes',array_merge($salesFilters,['format'=>'pdf'])) ?>">Exporter PDF</a><span class="ml-auto self-center text-sm text-slate-500"><?= count($mobileSales) ?> vente(s)</span></div></form>
 <?php endif; ?>
 <div class="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><form class="surface-panel h-fit space-y-4" method="post" action="<?= $url($isSupply?'/forfaits-unites/approvisionnements':'/forfaits-unites/ventes') ?>"><div><p class="text-xs font-black uppercase tracking-[.16em] <?= $isSupply?'text-blue-700':'text-violet-700' ?>"><?= $isSupply?'Entrée de solde':'Sortie de solde' ?></p><h2 class="mt-2 text-xl font-bold"><?= $isSupply?'Nouvel approvisionnement':'Nouvelle vente mobile' ?></h2></div><?php if($isSupply): ?><label class="form-field"><span>Fournisseur</span><input name="fournisseur" required></label><?php else: ?><label class="form-field"><span>Numéro client</span><input name="numero_client" placeholder="+243..."></label><?php endif; ?><label class="form-field"><span>Opérateur</span><select name="operator_id" required data-mobile-operator><option value="">Sélectionner</option><?php foreach($operators as $o): ?><option value="<?= (int)$o['id'] ?>"><?= $safe($o['nom']) ?></option><?php endforeach; ?></select></label><label class="form-field"><span>Produit</span><select name="product_id" required data-mobile-product><option value="">Sélectionner</option><?php foreach($mobileProducts as $p): ?><option value="<?= (int)$p['id'] ?>" data-operator="<?= (int)$p['operator_id'] ?>"><?= $safe($p['nom'].' · '.$p['unite']) ?></option><?php endforeach; ?></select></label><div class="grid grid-cols-2 gap-3"><label class="form-field"><span>Quantité</span><input name="quantite" type="number" min="0.01" step="0.01" required></label><label class="form-field"><span>Montant</span><input name="montant" type="number" min="0" step="0.01"></label></div><label class="form-field"><span>Commission</span><input name="commission" type="number" min="0" step="0.01"></label><?php if($isSupply): ?><label class="form-field"><span>Date</span><input name="date_operation" type="date" value="<?= date('Y-m-d') ?>" required></label><?php endif; ?><label class="form-field"><span>Référence</span><input name="reference" value="<?= $safe(($isSupply?'APP-':'VTE-').date('Ymd-His')) ?>" required></label><button class="btn-primary w-full"><?= $isSupply?'Enregistrer l’approvisionnement':'Valider la vente' ?></button></form>
 <section class="surface-panel overflow-hidden p-0"><div class="p-5"><h2 class="text-xl font-bold">Historique complet</h2><p class="mt-1 text-sm text-slate-500"><?= $isSupply?'Toutes les entrées de stock virtuel.':'Toutes les ventes et sorties de soldes.' ?></p></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><?php if($isSupply): ?><th>Fournisseur</th><?php else: ?><th>Client</th><?php endif; ?><th>Opérateur</th><th>Produit</th><th>Quantité</th><th>Montant</th><th>Commission</th><th>Date</th><th>Référence</th></tr></thead><tbody><?php foreach($isSupply?$mobileSupplies:$mobileSales as $row): ?><tr><td><?= $safe($isSupply?$row['fournisseur']:$row['numero_client']) ?></td><td><?= $safe($row['operator_name']) ?></td><td><?= $safe($row['product_name']) ?></td><td class="font-black"><?= $fmt($row['quantite']) ?> <?= $safe($row['unite']) ?></td><td><?= $fmt($row['montant']) ?></td><td><?= $fmt($row['commission']) ?></td><td><?= $safe($row['date_operation']) ?></td><td><?= $safe($row['reference']) ?></td></tr><?php endforeach; ?><?php if(!($isSupply?$mobileSupplies:$mobileSales)): ?><tr><td colspan="8" class="py-10 text-center text-slate-500">Aucune opération enregistrée.</td></tr><?php endif; ?></tbody></table></div></section></div>
 <?php endif; ?>
</section>
<script>document.querySelectorAll('[data-mobile-units] form').forEach(form=>{const operator=form.querySelector('[data-mobile-operator]'),product=form.querySelector('[data-mobile-product]');if(!operator||!product)return;const options=[...product.options];operator.addEventListener('change',()=>{product.value='';options.forEach(option=>{if(!option.value)return;option.hidden=option.dataset.operator!==operator.value;});});});document.querySelectorAll('[data-mobile-product-edit]').forEach(button=>button.addEventListener('click',()=>{const modal=document.querySelector(`[data-mobile-product-modal="${button.dataset.mobileProductEdit}"]`);modal?.classList.remove('hidden');modal?.classList.add('flex');}));document.querySelectorAll('[data-mobile-product-close]').forEach(button=>button.addEventListener('click',()=>{const modal=button.closest('[data-mobile-product-modal]');modal?.classList.add('hidden');modal?.classList.remove('flex');}));</script>
<script>
(() => {
 const source=document.querySelector('[data-mobile-supplies-json]');if(!source)return;const form=document.querySelector('form[action$="/forfaits-unites/approvisionnements"]');if(!form)return;form.classList.add('mobile-supply-form');
 const amount=form.querySelector('[name="montant"]');if(amount){const row=document.createElement('span');row.className='flex gap-2';amount.parentNode.insertBefore(row,amount);row.appendChild(amount);amount.classList.add('field-control','min-w-0','flex-1');const currency=document.createElement('select');currency.name='devise';currency.className='field-control shrink-0';currency.style.width='6rem';currency.innerHTML='<option value="CDF">CDF</option><option value="USD">USD</option>';currency.setAttribute('aria-label','Devise de l’approvisionnement');row.appendChild(currency);const note=document.createElement('small');note.className='mt-2 block text-xs text-slate-500';note.textContent='La devise s’applique au montant et à la commission.';amount.closest('label')?.appendChild(note);}
 let supplies=[];try{supplies=JSON.parse(source.textContent||'[]')}catch(e){}const table=document.querySelector('[data-mobile-supplies-json] ~ .grid table.data-table');if(!table)return;const headers=table.querySelectorAll('th');if(headers[4])headers[4].textContent='Montant saisi';if(headers[5])headers[5].textContent='Commission saisie';table.querySelectorAll('tbody tr').forEach((row,index)=>{const item=supplies[index],cells=row.cells;if(!item||cells.length<8)return;const currency=item.devise_saisie||'CDF',format=value=>new Intl.NumberFormat('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0));cells[4].textContent=`${format(item.montant_saisi??item.montant)} ${currency}`;cells[5].textContent=`${format(item.commission_saisie??item.commission)} ${currency}`;});
})();
</script>
<script>
(() => {
 const source=document.querySelector('[data-mobile-products-json]');if(!source)return;let products=[];try{products=JSON.parse(source.textContent||'[]')}catch(e){}
 const addCurrency=(form,product=null)=>{if(!form||form.querySelector('[name="devise_prix"]'))return;const unit=form.querySelector('[name="unite"]');if(!unit)return;const label=document.createElement('label');label.className='form-field';label.innerHTML='<span>Devise des prix</span><select name="devise_prix"><option value="CDF">CDF</option><option value="USD">USD</option></select>';unit.closest('label')?.after(label);const currency=label.querySelector('select');currency.value=product?.devise_prix||'CDF';if(product){const purchase=form.querySelector('[name="prix_achat"]'),sale=form.querySelector('[name="prix_vente"]');if(purchase)purchase.value=product.prix_achat_saisi??product.prix_achat??0;if(sale)sale.value=product.prix_vente_saisi??product.prix_vente??0;}};
 addCurrency(document.querySelector('form[action$="/forfaits-unites/produits"]'));
 document.querySelectorAll('[data-mobile-product-modal]').forEach(modal=>{const product=products.find(item=>Number(item.id)===Number(modal.dataset.mobileProductModal));addCurrency(modal.querySelector('form'),product);});
 document.querySelectorAll('[data-mobile-product-edit]').forEach(button=>{const id=button.dataset.mobileProductEdit,product=products.find(item=>Number(item.id)===Number(id)),cell=button.closest('td');if(!cell||cell.dataset.actionsReady)return;cell.dataset.actionsReady='1';cell.classList.add('flex','flex-wrap','gap-2');const toggle=document.createElement('form');toggle.method='post';toggle.action=`<?= $url('/forfaits-unites/produits') ?>/${id}/toggle`;toggle.innerHTML=`<button class="h-9 rounded-lg px-3 text-xs font-bold ${Number(product?.actif)===1?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}" type="submit">${Number(product?.actif)===1?'Désactiver':'Activer'}</button>`;cell.appendChild(toggle);const remove=document.createElement('form');remove.method='post';remove.action=`<?= $url('/forfaits-unites/produits') ?>/${id}/delete`;remove.addEventListener('submit',event=>{if(!confirm('Supprimer définitivement ce produit ?'))event.preventDefault();});remove.innerHTML='<button class="h-9 rounded-lg bg-red-50 px-3 text-xs font-bold text-red-700" type="submit">Supprimer</button>';cell.appendChild(remove);});
 document.querySelectorAll('[data-mobile-product-edit]').forEach(button=>{const product=products.find(item=>Number(item.id)===Number(button.dataset.mobileProductEdit)),cells=button.closest('tr')?.cells;if(!product||!cells)return;const currency=product.devise_prix||'CDF',format=value=>new Intl.NumberFormat('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0));cells[3].textContent=`${format(product.prix_achat_saisi??product.prix_achat)} ${currency}`;cells[4].textContent=`${format(product.prix_vente_saisi??product.prix_vente)} ${currency}`;});
})();
</script>
<script>
(() => {
 const form=document.querySelector('[data-quick-sale-form]');if(!form)return;
 const amountField=form.querySelector('[data-quick-amount]');if(amountField){const row=document.createElement('span');row.className='flex gap-2';amountField.parentNode.insertBefore(row,amountField);row.appendChild(amountField);amountField.classList.add('field-control','min-w-0','flex-1');const currency=document.createElement('select');currency.name='devise';currency.className='field-control shrink-0';currency.style.width='6rem';currency.setAttribute('aria-label','Devise');currency.innerHTML='<option value="CDF">CDF</option><option value="USD">USD</option>';row.appendChild(currency);const quick=document.createElement('input');quick.type='hidden';quick.name='quick_sale';quick.value='1';form.appendChild(quick);}
 const search=form.querySelector('[data-mobile-customer-search]'),id=form.querySelector('[data-mobile-customer-id]'),results=form.querySelector('[data-mobile-customer-results]'),add=form.querySelector('[data-mobile-customer-add]'),create=form.querySelector('[data-mobile-customer-create]'),phone=form.querySelector('[data-mobile-customer-phone]');
 let customers=[];try{customers=JSON.parse(document.querySelector('[data-mobile-customers-json]')?.textContent||'[]')}catch(e){}
 const normalize=value=>String(value||'').trim().toLocaleLowerCase('fr');
 const select=customer=>{search.value=customer.nom||'';id.value=customer.id||'';results.classList.add('hidden');add.classList.add('hidden');create.classList.add('hidden');};
 const render=()=>{id.value='';const query=normalize(search.value);results.innerHTML='';create.classList.add('hidden');if(!query){results.classList.add('hidden');add.classList.add('hidden');return;}const matches=customers.filter(c=>normalize(`${c.nom} ${c.telephone||''}`).includes(query)).slice(0,6);matches.forEach(c=>{const button=document.createElement('button');button.type='button';button.className='block w-full border-b border-slate-100 px-4 py-3 text-left text-sm hover:bg-violet-50';button.textContent=`${c.nom}${c.telephone?' · '+c.telephone:''}`;button.addEventListener('click',()=>select(c));results.appendChild(button);});results.classList.toggle('hidden',matches.length===0);const exact=customers.some(c=>normalize(c.nom)===query||normalize(c.telephone)===query);add.classList.toggle('hidden',exact||query.length<2);};
 search.addEventListener('input',render);search.addEventListener('focus',render);
 form.addEventListener('submit',()=>{const amount=form.querySelector('[data-quick-amount]'),quantity=form.querySelector('[data-quick-quantity]');if(amount&&quantity)quantity.value=amount.value;});
 add.addEventListener('click',()=>{results.classList.add('hidden');add.classList.add('hidden');create.classList.remove('hidden');phone.value=form.numero_client.value||'';phone.focus();});
 form.querySelector('[data-mobile-customer-cancel]').addEventListener('click',()=>{create.classList.add('hidden');render();});
 form.querySelector('[data-mobile-customer-save]').addEventListener('click',async event=>{const button=event.currentTarget,name=search.value.trim();if(!name)return;button.disabled=true;button.textContent='Enregistrement...';try{const response=await fetch(form.dataset.customerEndpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({nom:name,telephone:phone.value.trim()})});const payload=await response.json();if(!response.ok||!payload.customer)throw new Error(payload.message||'Création impossible.');customers=payload.customers||[...customers,payload.customer];select(payload.customer);}catch(error){alert(error.message);}finally{button.disabled=false;button.textContent='Enregistrer';}});
})();
</script>
