<?php
$workspace = is_array($workspace ?? null) ? $workspace : [];
$products = is_array($products ?? null) ? $products : [];
$workspaceStats = is_array($workspaceStats ?? null) ? $workspaceStats : [];
$safe = static fn ($value, string $fallback = '—'): string => htmlspecialchars((string) (($value ?? '') !== '' ? $value : $fallback), ENT_QUOTES, 'UTF-8');
?>
<section class="space-y-5">
    <div class="relative overflow-hidden rounded-2xl bg-gradient-to-br <?= $safe($workspace['gradient'] ?? 'from-slate-950 to-teal-800') ?> p-6 text-white shadow-xl sm:p-8">
        <div class="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-white/10 blur-3xl"></div>
        <div class="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div class="max-w-3xl"><div class="mb-5 flex items-center gap-3"><span class="grid h-14 w-14 place-items-center rounded-2xl border border-white/20 bg-white/10 text-2xl"><?= $safe($workspace['icon'] ?? '◼') ?></span><div><p class="text-xs font-black uppercase tracking-[.2em] text-white/75"><?= $safe($workspace['eyebrow']) ?></p><p class="mt-1 text-sm text-white/55">Espace métier dédié</p></div></div><h1 class="text-3xl font-black tracking-tight sm:text-4xl"><?= $safe($workspace['title']) ?></h1><p class="mt-4 max-w-2xl text-sm leading-7 text-white/75">Un environnement adapté à votre activité pour gérer le catalogue, les disponibilités et les opérations essentielles.</p></div><div class="flex flex-col gap-3 sm:flex-row"><a class="rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-center text-sm font-bold hover:bg-white/20" href="<?= $url('/stock/movements') ?>">Voir le stock</a><a class="rounded-xl bg-white px-5 py-3 text-center text-sm font-black text-slate-950 shadow-lg hover:bg-slate-100" href="<?= $url('/products/create') ?>">Ajouter : <?= $safe($workspace['unit']) ?></a></div></div>
    </div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><?php foreach ([['Références',(int)($workspaceStats['total']??0),'text-slate-950'],['Actives',(int)($workspaceStats['active']??0),'text-teal-700'],['Stock critique',(int)($workspaceStats['low']??0),'text-amber-700'],['Ruptures',(int)($workspaceStats['out']??0),'text-red-700']] as [$label,$value,$color]): ?><article class="stat-card"><p class="text-sm text-slate-500"><?= $safe($label) ?></p><p class="mt-2 text-3xl font-black <?= $color ?>"><?= $value ?></p></article><?php endforeach; ?></div>
    <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]">
        <section class="surface-panel overflow-hidden p-0"><div class="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-teal-700">Catalogue métier</p><h2 class="mt-2 text-xl font-bold">Catalogue et disponibilités</h2></div><a class="btn-secondary" href="<?= $url('/products') ?>">Gestion complète</a></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Référence</th><th>Catégorie</th><th>Prix de vente</th><th>Stock</th><th>Seuil</th><th>Statut</th><th class="text-right">Action</th></tr></thead><tbody><?php foreach ($products as $product): $stock=(int)($product['quantite_stock']??0);$min=(int)($product['alerte_stock_min']??0); ?><tr><td><strong class="text-slate-950"><?= $safe($product['nom']) ?></strong><span class="mt-1 block text-xs text-slate-500"><?= $safe($product['ref']) ?></span></td><td><?= $safe($product['category_name']??'Sans catégorie') ?></td><td class="font-bold"><?= number_format((float)($product['prix_vente_montant']??$product['prix_vente']??0),2,',',' ') ?> <?= $safe($product['prix_vente_devise']??'USD') ?></td><td class="text-lg font-black"><?= $stock ?></td><td><?= $min ?></td><td><span class="rounded-lg px-2 py-1 text-xs font-bold <?= $stock===0?'bg-red-100 text-red-700':($stock<=$min?'bg-amber-100 text-amber-700':'bg-teal-100 text-teal-700') ?>"><?= $stock===0?'Rupture':($stock<=$min?'Alerte':'Disponible') ?></span></td><td class="text-right"><a class="btn-secondary h-10 w-auto px-3 text-xs" href="<?= $url('/products/'.(int)$product['id']) ?>">Consulter</a></td></tr><?php endforeach; ?><?php if($products===[]): ?><tr><td colspan="7" class="py-12 text-center text-sm font-semibold text-slate-500">Aucune référence enregistrée dans cet espace.</td></tr><?php endif; ?></tbody></table></div></section>
        <aside class="space-y-5"><section class="surface-panel"><p class="text-xs font-black uppercase tracking-[.16em] text-teal-700">Priorités métier</p><div class="mt-4 space-y-3"><?php foreach((array)($workspace['focus']??[]) as $focus): ?><div class="flex items-center gap-3 rounded-xl bg-slate-50 px-4 py-3"><span class="h-2 w-2 rounded-full bg-teal-500"></span><span class="text-sm font-bold text-slate-700"><?= $safe($focus) ?></span></div><?php endforeach; ?></div></section><section class="rounded-2xl bg-slate-950 p-5 text-white"><h2 class="font-bold">Accès rapides</h2><div class="mt-4 space-y-2 text-sm"><a class="block rounded-xl bg-white/10 px-4 py-3 font-bold hover:bg-white/20" href="<?= $url('/pos') ?>">Caisse et ventes</a><a class="block rounded-xl bg-white/10 px-4 py-3 font-bold hover:bg-white/20" href="<?= $url('/supplies') ?>">Approvisionnements</a><a class="block rounded-xl bg-white/10 px-4 py-3 font-bold hover:bg-white/20" href="<?= $url('/rapports/ventes') ?>">Rapports</a></div></section></aside>
    </div>
</section>
